# Generated by Django 4.2.2 on 2023-06-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='products',
        ),
    ]
